#!/bin/sh
# ###########################################################################
# Script generated by Fortify Scan Wizard (c) 2011-2026 Open Text
# Created on 2026/03/05 17:43:40
# ###########################################################################
# Generated for the following languages:
# 	Gradle
# 	Java
# 	Java Bytecode
# ###########################################################################
# FPR - the name of analysis results file
# DEBUG - if set to true, runs SCA in debug mode
# SOURCEANALYZER - the name of the SCA executable
# BUILDID - the SCA build ID
# ARGFILE - the name of the argument file that's passed to SCA
# BYTECODE_ARGFILE - the name of the argument file for Java bytecode translation in the SCA
# MEMORY - the memory settings for SCA
# SCANSWITCHES - parameters to pass in the SCA analysis phase
# LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
# OLDFILENUMBER - this defines the file that contains the number of files within the project, it is automatically generated
# FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
# ###########################################################################

ENV=$1 
echo "Fortify scan environment = $ENV"

DEBUG=false
SOURCEANALYZER=sourceanalyzer
BUILDID="FSAP-MODEL"
REPORT_PATH="/var/jenkins_home/Fortify/reports/$BUILDID/$ENV/$(date +%Y%m%d_%H%M%S)"
FPR="$REPORT_PATH/$BUILDID.fpr"
ARGFILE="Fortify-FSAP-MODEL.sh.args"
BYTECODE_ARGFILE="Fortify-FSAP-MODEL.sh.bytecode.args"
MEMORY="-Xmx14165M -Xms400M -Xss24M "

LAUNCHERSWITCHES=""
SCANSWITCHES=""
OLDFILENUMBER="Fortify-FSAP-MODEL.sh.fileno"
FILENOMAXDIFF=10
ENABLE_BYTECODE=false

mkdir -p "/var/jenkins_home/Fortify/reports/$BUILDID/$ENV/$(date +%Y%m%d_%H%M%S)"

export PATH="/var/jenkins_home/Fortify/OpenText_SAST_Fortify_26.1.0/bin:$PATH"
export PATH="/var/jenkins_home/Fortify/OpenText_Application_Security_Tools_25.4.0/bin:$PATH"

PROJECTROOT0="/var/jenkins_home/workspace/FORTIFY-FSAP-MODEL"
if [ ! -d "$PROJECTROOT0" ]; then
   echo  "ERROR: This script is being run on a different machine than it was"
   echo  "       generated on or the targeted project has been moved. This script is "
   echo  "       configured to locate files at"
   echo  "          $PROJECTROOT0"
   echo  "       Please modify the \$PROJECTROOT0 variable found"
   echo  "       at the top of this script to point to the corresponding directory"
   echo  "       located on this machine."
   exit
fi

if [ $DEBUG = true ]; then export LAUNCHERSWITCHES="-debug $LAUNCHERSWITCHES"; fi
echo Extracting Arguments File


grep "# ARGS" $0 | grep -v grep | cut -d" " -f3- | sed -e s#PROJECTROOT0_MARKER#"$PROJECTROOT0"#g   > $ARGFILE

grep "# BYTECODE_ARGS" $0 | grep -v grep | cut -d" " -f3- | sed -e s#PROJECTROOT0_MARKER#"$PROJECTROOT0"#g   > $BYTECODE_ARGFILE

if [ -s $BYTECODE_ARGFILE ]; then
ENABLE_BYTECODE=true
fi
# ###########################################################################
echo Cleaning previous scan artifacts
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID -clean 
if [ $? -ne 0 ] ; then
echo sourceanalyzer failed, exiting
exit 1
fi
# ###########################################################################
echo Running Build Integration
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID -source 17 -Dfortify.sca.sqlType=TSQL ./gradlew model-grpc-common:clean model-grpc-common:build -x publishToMavenLocal -x check --stacktrace --console=plain --offline
if [ $? -ne 0 ] ; then
echo sourceanalyzer Build failed, exiting
exit 1
fi
# ###########################################################################
echo Translating files
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID @$ARGFILE
if [ $? -ne 0 ] ; then
echo sourceanalyzer failed, exiting
exit 1
fi
# ###########################################################################
if [ $ENABLE_BYTECODE = true ]; then
echo Translating Java bytecode files
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID @$BYTECODE_ARGFILE
if [ $? -ne 0 ] ; then
echo sourceanalyzer failed, exiting
exit 1
fi
fi
# ###########################################################################
echo Testing Difference between Translations
FILENUMBER=`$SOURCEANALYZER -b $BUILDID -show-files | wc -l`

if [ ! -f $OLDFILENUMBER ]; then
	echo It appears to be the first time running this script, setting $OLDFILENUMBER to $FILENUMBER
	echo $FILENUMBER > $OLDFILENUMBER
else
	OLDFILENO=`cat $OLDFILENUMBER`
	DIFF=`expr $OLDFILENO "*" $FILENOMAXDIFF`
	DIFF=`expr $DIFF /  100`

	MAX=`expr $OLDFILENO + $DIFF`
	MIN=`expr $OLDFILENO - $DIFF`

	if [ $FILENUMBER -lt $MIN ] ; then SHOWWARNING=true; fi
	if [ $FILENUMBER -gt $MAX ] ; then SHOWWARNING=true; fi

	if [ -n "$SHOWWARNING" ] && [ "$SHOWWARNING" = true ] ; then
		echo "WARNING: The number of files has changed by over $FILENOMAXDIFF%, it is recommended"
		echo "         that this script is regenerated with the ScanWizard"
	fi

	echo $MAX $MIN $DIFF
fi;

# ###########################################################################
echo Starting scan
$SOURCEANALYZER $MEMORY $LAUNCHERSWITCHES -b $BUILDID $SCANSWITCHES -scan -f $FPR
if [ $? -ne 0 ] ; then
echo sourceanalyzer failed, exiting
exit 1
fi
# ###########################################################################
echo Starting generate reports
# OWASP Top 10
BIRTReportGenerator \
    -source "$FPR" \
    -output "$REPORT_PATH/$BUILDID OWASPTop10.pdf" \
    -format "PDF" \
    -template "OWASP Top 10" \
    --SecurityIssueDetails
BIRTReportGenerator \
    -source "$FPR" \
    -output "$REPORT_PATH/$BUILDID OWASPTop10.html" \
    -format "HTML" \
    -template "OWASP Top 10" \
    --SecurityIssueDetails
# DeveloperWorkbook
BIRTReportGenerator \
        -source "$FPR" \
        -output "$REPORT_PATH/$BUILDID DeveloperWorkbook.pdf" \
        -format "PDF" \
        -template "Developer Workbook"
BIRTReportGenerator \
        -source "$FPR" \
        -output "$REPORT_PATH/$BUILDID DeveloperWorkbook.html" \
        -format "HTML" \
        -template "Developer Workbook"
# ###########################################################################
echo Finished
# ARGS "-cp"
# ARGS "PROJECTROOT0_MARKER/etc/boot/lib/hello-world-boot-starter.jar:PROJECTROOT0_MARKER/gradle/wrapper/gradle-wrapper.jar"
# ARGS "-source"
# ARGS "17"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.gradle"
# ARGS "-exclude" "PROJECTROOT0_MARKER/gradle.properties"
# ARGS "-exclude" "PROJECTROOT0_MARKER/gradle/wrapper/gradle-wrapper.properties"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.jar"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.xml"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.xsd"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.xmi"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.wsdd"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/*.config"
# ARGS "-exclude" "PROJECTROOT0_MARKER/**/git.properties"
# ARGS "PROJECTROOT0_MARKER"
